[id]
name = "Teon L Brooks, Ph.D"
descriptors = ["Researcher", "Scientist", "Technologist"]
imageURL = "https://0.gravatar.com/avatar/8179ec2a3461f51e568637a913b4061ebc7d6d31d7a1aad43d0e251b1fe42c0b?size=1000"
# imageURL = "images/home.jpg"
[[id.occupations]]
title = 'Cofounder'
organization = 'Gotham Data Clinic'
website = "https://gothamdataclinic.org"

[[id.occupations]]
title = 'Principal Consultant'
organization = 'datalus'
website = ""

[skills]

natural_languages =	["English (native)", "French (B2)", "Portuguese (B1)"]
programming_languages =	["Python (adv.)", "R (adv.)", "JavaScript (int.)"]

[[positions]]
filename = "bids.png"
organization = "Brain Imaging Data Structure"
title = "BIDS-MEG contributor"
timespan = "2017-2020"
description = """
"""
website = "https://bids.neuroimaging.io"
category = ["Past Projects", "Open Source"]

[[positions]]
filename = "brainwaves.png"
organization = "BrainWaves"
title = "President of Advisory Board"
timespan = "2017-2022"
description = """
*President of Advisory Board*

*Product Manager*

Democratizing Cognitive Science
"""
website = "https://wp.nyu.edu/brainwaves/"
category = ["Past Projects", "Volunteer", "Education"]

[[positions]]
# correct the icon
filename = "openbci.png"
organization = "DIYSciThai"
title = "Workshop Creator; Co-organizer"
timespan = "2016"
description = """
DIYSciThai was an Open Science workshop taught in Bangkok, Thailand in June 2016. 
This two-day workshop is the basis of an open science initiative to provide an 
integrative curriculum to teach cognitive science through experiential learning.

This DIY workshop featured building research electronics (eye-tracker and EEG) from open-source hardware, and low-cost electronics.

This workshop was supported by grants from Fulbright Thailand, the Open and Collaborative Science in Development Network (OCSDnet), 
and NYU. 

[Photos](https://photos.app.goo.gl/4zGBCM5C634B4nf9A)
[Project Summary](https://github.com/teonbrooks/DIYSciThai)
"""
website = "https://github.com/teonbrooks/DIYSciThai"
category = ["Past Projects", "Education"]

[[positions]]
filename = "chateaubriand.png"
organization = "French Embassy to the U.S."
title = "STEM Fellow"
timespan = "2017-2018"
description = """
Fellowship to conduct dissertation research in France.
"""
website = "https://chateaubriand-fellowship.org/"
category = "Fellowships"

[[positions]]
filename = "ciel.png"
organization = "Gotham Data Clinic"
title = "Executive Director"
timespan = "2019-Present"
description = """
"""
website = "https://gothamdataclinic.org"
category = "Current Orgs"

[[positions]]
filename = "covenant.png"
organization = "Carolina Covenant"
title = "Scholar"
timespan = "2006-2009"
description = """
Funding initiative for low-income students to graduate 
from college debt-free through grants, scholarships, and work-study.
"""
website = "https://www.unc.edu/story/carolina-covenant/"
category = "Fellowships"

[[positions]]
filename = "firefox.png"
organization = "Mozilla"
title = "Staff Data Scientist"
timespan = "2017-2022, 2024-Present"
description = """
*Revenue Intelligence (2024-Present)*

- Conduct experimentation for new machine-learning-powered experiences in 
address bar in the Firefox browser.

- Conduct large-scale data analyses across hundreds of millions of users for our 
revenue-producing products and our advertising business.

*Product Management, ML (2021-2022)*

- Led new product development to incorporate on-device machine learning in applications.

- Enabled robust telemetry instrumentation to enable contextual recommendation within Firefox.

- Mentored students at the AUC Data Science Initiative on responsible and trustworthy AI within product development and design.


*Product Data Science (2017-2021)*

- Conducted experimentation for new product development for the address bar in the Firefox browser.

- Conducted large-scale data analysis, and modeling across hundreds of millions of users using non-parametric methods.

- Used mixed methods of browser telemetry data and user surveys to surface user insights for product recommendations.

- Mentored two data scientist interns on exploratory data analysis and data science practices.

- Launched and managed the [Data@Mozilla blog](https://blog.mozilla.org/data).

"""
website = "https://mozilla.org"
category = "Current Orgs"
# from Ben's LinkedIn
# Technical lead of the Revenue and Search data science team. 
# Partnered with Product, Business Development and Finance teams to create alignment around revenue+search metrics. 
# Oversaw dozens of experiments & extensively researched the relationship between revenue and user behavior.

[[positions]]
filename = "FoR.png"
organization = "Future of Research"
title = "Board Member"
timespan = "2017-2018"
description = """
Served on the board of a nonprofit advocacy group 
for early-career scientists.

[Board Alumni](https://www.futureofresearch.org/boardalumnae/)
"""
website = "https://futureofresearch.org"
category = ["Past Orgs", "Volunteer"]

[[positions]]
filename = "grfp.png"
organization = "National Science Foundation Graduate Research Fellowship Program"
title = "NSF Graduate Research Fellow"
timespan = "2011-2016"
description = """
Fellowship recipient in prestigious national competition 
for graduate-level STEM Research.
"""
website = "https://nsfgrfp.org"
category = "Fellowships"

[[positions]]
filename = "mfs.png"
organization = "March for Science"
title = "National Co-Organizer: Co-Director of Partnerships"
timespan = "2017"
description = """
- Co-led a team to build a coalition of >300 scientific
societies, NGOs, science museums, and non-profits to mobilize their
members to march. 

- Organized and coordinated one of the largest science
demonstration with 100k marchers in Washington, DC and over a million marchers in
610 cities worldwide.
"""
website = "https://marchforscience.org"
category = ["Past Orgs", "Volunteer"]

[[positions]]
filename = "msl.png"
organization = "Mozilla Science Lab"
title = "Fellow for Open Science"
timespan = "2016-2017"
description = """
10-month fellowship
"""
website = "https://wiki.mozilla.org/ScienceLab"
category = "Fellowships"

[[positions]]
filename = "mne.png"
organization = "MNE-tools"
title = "Core Contributor"
timespan = "2012-2017"
description = """
*MNE-Python: Core Contributor (2012-2017)*

MEG and EEG Data Processing and Analysis Package in Python.

*MNE-Realtime: Maintainer (2019-2023)*

Supported realtime data analysis with support for LSL and FieldTrip clients.
This project has been deprecated and superseded by 
[mne-lsl](https://mne.tools/mne-lsl/).

*MNE-BIDS: Core Contributor (2017-2020)*
Read and write BIDS-compatible datasets with the help of MNE-Python in Python.
"""
website = "https://mne.tools"
category = ["Past Projects", "Volunteer", "Open Source"]

[[positions]]
filename = "nyu.png"
organization = "New York University"
title = "PhD"
timespan = "2011-2017"
description = """
*PhD (2011-2017)*

Experimental Psychology: Cognition and Perception

*President, NYU Cog Collective (2015-2017)*
Cofounder of student organization representing the Cognition and Perception program.
We thought workshops and hosted socials [link](https://github.com/nyu-cogcollective).

*Master of Arts (2011-2013)
Experimental Psychology: Cognition and Perception
"""
website = "https://as.nyu.edu/psychology.html"
category = "Education"

[[positions]]
filename = "openbci.png"
organization = "OpenBCI"
title = "Research Scientist Consultant"
timespan = ""
description = """
Research consultant for EEG data analysis and software design.
"""
website = "https://openbci.com"
category = "Past Orgs"

[[positions]]
filename = "openexp.png"
organization = "OpenEXP"
title = "Product Manager"
timespan = "2015-2016"
description = """
EEG Experimentation Platform
"""
website = "https://github.com/OpenEXP/OpenEXP"
category = ["Past Projects", "Volunteer"]

[[positions]]
filename = "queerhack.png"
organization = "QueerHack"
title = ""
timespan = ""
description = """
"""
website = ""
category = "Past Orgs"

[[positions]]
filename = "recurse.png"
organization = "The Recurse Center"
title = "Recurser"
timespan = "2023"
description = """
Summer 1 Half-Batch.
Projet Vie.
"""
website = "https://recurse.com"
category = "Past Orgs"

[[positions]]
filename = "shd.png"
organization = "Science Hack Day"
title = "Co-Organizer"
timespan = "2017"
description = """
"""
website = ""
category = ["Past Orgs", "Volunteer"]

[[positions]]
filename = "stanford.png"
organization = "Stanford University"
title = "Mozilla Fellow/Postdoctoral Scholar"
timespan = "2016-2017"
description = """
Co-organizer for the March for Science.
BIDS-MEG extension.
MNE-BIDS development.
"""
website = "https://stanford.edu"
category = "Education"

[[positions]]
filename = "telecom.png"
organization = "Telecom ParisTech"
title = "Chateaubriand STEM Fellow"
timespan = "2014-2015"
description = """
"""
website = ""
category = "Education"

[[positions]]
filename = "trainer-hex.png"
organization = "RStudio"
title = "Certified Trainer"
timespan = ""
description = """
"""
website = "https://education.rstudio.com/trainers/"
category = "Education"

[[positions]]
filename = "unc.png"
organization = "University of North Carolina"
title = "Bachelor of Science"
timespan = "2005-2009"
description = """
Double Major in Psychology and Linguistics
"""
website = "https://unc.edu"
category = "Education"

[[positions]]
filename = "unesco.png"
organization = "UNESCO"
title = "Intern"
timespan = "2015"
description = """
Intern in the Science Department.
"""
website = ""
category = ["Volunteer"]

[[positions]]
# correct the icon
filename = "braiNY-SFN.png"
organization = "Greater NYC Chapter of Society for Neuroscience"
title = "Co-Chair"
timespan = "2015-2016"
description = """
"""
website = ""
category = ["Volunteer"]

[[positions]]
filename = "bkcb1.png"
organization = "New York City Community Board (BKCB1)"
title = "Board Member"
timespan = "2020-2022"
description = """
I served on the Capital Budget Committee, the Board Budget Committee, the Education committee, and the Outreach Committee.

I created and managed the community board Twitter account (@BrooklynCB1).
"""
website = ""
category = ["Volunteer", "Civic Engagement"]

[[positions]]
filename = "american.png"
organization = "American University"
title = "Senior Adjunct Professorial Lecturer"
timespan = "2021"
description = """
Statistical Programming: R + Tidyverse
"""
website = ""
category = ["Past Orgs"]

[[positions]]
filename = "aimlabs.png"
organization = "State Space Labs"
title = "VP, Head of Research and Development"
timespan = "2022"
description = """
- Delivered and launched a mouse sensitivity finder for first-person shooter gaming 
in a joint product venture between the core product team and R&D based on my teamâ€™s research.

- Led a team of five research scientists to incorporate innovative research into Aim Lab, 
the flagship aim trainer product. 

- Led and coordinated digital health initiatives to create cognitive assessments for 
altered states of consciousness such as concussion.
"""
website = "aimlabs.com"
category = "Past Orgs"

# [[positions]]
# filename = ""
# organization = "New York Cares"
# title = "math tutor"
# timespan = "2013"
# description = """
# """
# website = ""
# category = ""


# [[positions]]
# filename = ""
# organization = ""
# title = ""
# timespan = ""
# description = """
# """
# website = ""
# category = ""

